feat: Add a "Select all" for the filters
yearn/ySync pull request #113
Opened 2023-08-07 10:58 UTC by karelianpie

## Description

Add a new checkbox to (de)select all filters

## Related Issue

Closes https://github.com/yearn/ySync/issues/110

## Motivation and Context

Allow users to quickly select filters. Best use case is when a user wants just one filter, they can click on "Select all", then again and it will deselect all, then they can just select the one they are interested in.

## How Has This Been Tested?

Locally, checking/unchecking the chexkbox

## Screenshots (if appropriate):

<img width="1582" alt="Screenshot 2023-08-07 at 13 55 27" src="https://github.com/yearn/ySync/assets/78794805/21471fff-4398-4da5-9c28-cd55e5f61eda">

<img width="1582" alt="Screenshot 2023-08-07 at 13 55 31" src="https://github.com/yearn/ySync/assets/78794805/8be96c60-1c48-4d0a-9ab6-bebde41d270b">

2023-08-07 11:37 UTC, Majorfi requested changes
I would add a effect to catch when they are all selected manually 🙏

2023-08-07 12:01 UTC, karelianpie commented
> I would add a effect to catch when they are all selected manually 🙏

What's the expected behaviour?

* All filters checked => Select All checked
* No filters checked => Select All unchecked
* Partially filters checked => Select All unchecked

So "Select All" is only checked when all filters are checked, as soon as 1 becomes unchecked then the Select All becomes unchecked as well?

2023-08-07 12:39 UTC, karelianpie commented
> I would add a effect to catch when they are all selected manually 🙏

Done https://github.com/yearn/ySync/pull/113#issuecomment-1667726356 with https://github.com/yearn/ySync/pull/113/commits/10cfacff54af03a9021cd3bbf035f6eef1aa67a4

2023-08-07 16:02 UTC, 0xBasically submitted a review, later dismissed
lgtm!

2023-08-09 09:00 UTC, Majorfi requested changes

2023-08-09 09:00 UTC, Majorfi commented on pages/index.tsx
> +	}, [appSettings, set_appSettings]);
The use effect may call itself once appSettings is updated

Maybe best to do:
```suggestion
	useEffect((): void => {
		set_appSettings((prev) => {
			const isAllSelected = [
				prev.shouldShowMissingTranslations,
				prev.shouldShowIcons,
				prev.shouldShowPrice,
				prev.shouldShowRetirement,
				prev.shouldShowYearnMetaFile,
				prev.shouldShowLedgerLive,
				prev.shouldShowStrategies,
				prev.shouldShowRisk,
				prev.shouldShowRiskScore,
				prev.shouldShowDescriptions,
				prev.shouldShowAPY,
				prev.shouldShowWantTokenDescription
			].every(Boolean);
			return ({...prev, shouldShowAllFilters: isAllSelected})
		});
	}, [set_appSettings]);
```

2023-08-09 09:00 UTC, Majorfi commented on pages/index.tsx
> +	}, [appSettings, set_appSettings]);
+ I think `set_appSettings` is not required in effects!

2023-08-09 10:22 UTC, karelianpie commented on pages/index.tsx
> +	}, [appSettings, set_appSettings]);
Sounds good, had to type it a bit https://github.com/yearn/ySync/pull/113/commits/89896c38d7e0c50cda724e3e907b5d8f5a71a1ec

2023-08-10 07:57 UTC, Majorfi approved these changes

2023-08-10 07:57 UTC, merged