feat: Add check for meta/vaults/[network]
yearn/ySync pull request #54
Opened 2022-09-01 00:03 UTC by karelianpie

## Description

For each vaults, check if a file matching the vault address exists in yearn-meta/vaults/[network] and display an error if the file does not exist

## Related Issue

Closes https://github.com/yearn/ySync/issues/40

## Motivation and Context

We'd like to be warned when a vault does not have a corresponding file on https://github.com/yearn/yearn-meta/tree/master/data/vaults

## How Has This Been Tested?

Manually filtered an existing file from the GitHub file list and saw the error being displayed

## Screenshots (if appropriate):

<img width="637" alt="ySync" src="https://user-images.githubusercontent.com/78794805/187805360-47d8fe6d-5d77-4d3f-a2d1-7532539a53d5.png">

2022-09-02 09:43 UTC, Majorfi requested changes
Minor change required: yearn-meta is now deprecated for yDaemon!
I put some code suggestion that should work!
Thank you ser!

2022-09-02 09:43 UTC, Majorfi commented on contexts/useYearn.tsx
> +			axios.get(`https://api.github.com/repos/yearn/yearn-meta/contents/data/vaults/${_chainID}`)
Meta has been merged with yDaemon, we should use the new URL here!
```suggestion
			axios.get(`https://api.github.com/repos/yearn/ydaemon/contents/data/meta/vaults/${_chainID}`)
```

2022-09-02 09:43 UTC, Majorfi commented on components/VaultBox.tsx
> +						</a>
Meta has been merged with yDaemon, url need some change!
```suggestion
						<a href={`https://github.com/yearn/ydaemon/tree/master/data/meta/vaults/${chainID}`} target={'_blank'} className={'underline'} rel={'noreferrer'}>
							{`https://github.com/yearn/ydaemon/tree/master/data/meta/vaults/${chainID}`}
						</a>
```

2022-09-02 23:01 UTC, karelianpie commented
> Minor change required: yearn-meta is now deprecated for yDaemon! I put some code suggestion that should work! Thank you ser!

Thanks @Majorfi, just ran this locally and it all works as expected

2022-09-05 11:28 UTC, Majorfi approved these changes

2022-09-05 11:28 UTC, merged