feat: Make a toggle for Icon and Price
yearn/ySync pull request #93
Opened 2023-06-16 19:18 UTC by karelianpie

## Description

Make a toggle for Icon and Price

## Related Issue

Closes https://github.com/yearn/ySync/issues/92

## Motivation and Context

We want to show/hide icon and price fields

## How Has This Been Tested?

Locally

## Screenshots (if appropriate):

<img width="1582" alt="Screenshot 2023-06-16 at 22 17 25" src="https://github.com/yearn/ySync/assets/78794805/7674b5e2-cb0a-4744-bafb-4a2b8c02ccc1">
<img width="1582" alt="Screenshot 2023-06-16 at 22 17 21" src="https://github.com/yearn/ySync/assets/78794805/dfb19d5e-ab7f-4c09-ba3e-e3f84c1d2c91">

2023-06-19 07:33 UTC, Majorfi requested changes

2023-06-19 07:33 UTC, Majorfi commented on components/VaultEntity.tsx
> +						<b className={'mb-1 font-mono text-sm text-neutral-500'}>{'Missing stst'}</b>
stst?

2023-06-19 07:39 UTC, karelianpie commented on components/VaultEntity.tsx
> +						<b className={'mb-1 font-mono text-sm text-neutral-500'}>{'Missing stst'}</b>
Oops, nice catch. Fixed with https://github.com/yearn/ySync/pull/93/commits/0f2e98b49e8e1ad4cc075b59024e087d7d273c9a

2023-06-19 17:01 UTC, 0xBasically approved these changes
lgtm working locally

2023-06-20 07:23 UTC, Majorfi approved these changes

2023-06-20 07:24 UTC, merged